services:
  ros2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ros2_robot:jazzy-nvidia
    container_name: ros2_dev

    # NVIDIA GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, render, display]

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=burger
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # Tell Gazebo to use the NVIDIA GPU explicitly
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws/src:/ros2_ws/src
      - gazebo_models:/root/.gazebo

    network_mode: host
    ipc: host
    stdin_open: true
    tty: true

volumes:
  gazebo_models:
