<?xml version="1.0"?>
<package format="3">
  <name>smart_room_nodes</name>
  <version>0.0.1</version>
  <description>Python sensor nodes and C++ controller nodes for the Smart Room</description>
  <maintainer email="mdshams013@gmail.com">Shams</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>smart_room_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
